### PR TITLE
Create hi.md

### PR DESCRIPTION
**Pull request by jjgould94**
# Why? 
To say hi 
# How was this tested? 
Saw hi

### CODE REVIEW

**Review by natedemery — APPROVED** [review]
🤠

**Review by kyleroush — CHANGES_REQUESTED** [review]
Why is this only in English!!!it should use emojis the universal language

**Review by kyleroush — APPROVED** [review]

**Review by corymcdonald — CHANGES_REQUESTED** [review]
You need to have `hugo` either generate this or add a section with the title,
```md
---
title: "hi"
date: 2018-11-02T09:00:54-06:00
---
```

**Comment by jjgould94** [comment]
@corymcdonald  I did it: 
https://github.com/corymcdonald/blog/pull/2/commits/69d2448362dab63a5da050efde815f99fdb5e68

**Pull request merged**
