### PR TITLE
Change cory's name to cowboy emoji

### PR DESCRIPTION
**Pull request by natedemery**
🤠

### CODE REVIEW

**Comment by kyleroush** [comment]
is this deployed to netlify already?

**Comment by natedemery** [comment]
@kyleroush 🤠

**Review by jjgould94 — APPROVED** [review]
+1, can confirm cory has legally changed his name to 🤠

**Comment by natedemery** [comment]
I don't understand why this hasn't been merged yet???

**Comment by corymcdonald** [comment]
lgtm

**Comment by corymcdonald** [comment]
actually i need to revert this

**Comment by natedemery** [comment]
no

**Pull request merged**
